namespace JosephExperience;

/// <summary>
/// Static pools of lore-flavoured names and quotes drawn from the Naddaf IT mythology.
/// Used when importing new Joseph images: if the user leaves the name/quote blank,
/// we assign one entry at random and persist it so it sticks to that Joseph forever.
/// </summary>
public static class LorePools
{
    public static readonly string[] Names =
    [
        "Joseph Naddaf Has Entered Maximum IT Wizard Mode",
        "Mr Naddaf Has Determined That The User Is The Problem",
        "Joseph Naddaf Has Activated The Emergency Shawarma Protocol",
        "Mr Naddaf Has Returned To The Massage Chair",
        "Joseph Naddaf Has Arrived In The Honda Civic",
        "Mr Naddaf Has Been Summoned To Fix The Internet Again",
        "Joseph Naddaf Has Entered The Server Room",
        "Mr Naddaf Has Successfully Restarted The Device",
        "Joseph Naddaf Has Located The Missing Ethernet Cable",
        "Mr Naddaf Has Determined That Nobody Followed His Instructions",
        "Joseph Naddaf Has Finished Another Successful Shawarma Operation",
        "Mr Naddaf Has Entered Advanced Troubleshooting Mode",
        "Joseph Naddaf Has Determined That The Printer Is Guilty",
        "Mr Naddaf Has Asked Everyone To Stop Touching The Router",
        "Joseph Naddaf Has Achieved Perfect Technological Understanding",
        "Mr Naddaf Has Entered The Final Stage Of Troubleshooting",
        "Joseph Naddaf Has Returned From 540 Curseway",
        "Mr Naddaf Has Deployed The Sacred Restart",
        "Joseph Naddaf Has Detected An Unacceptable Lack Of Shawarma",
        "Mr Naddaf Has Successfully Restored The Network",
        "Joseph Naddaf Has Entered Honda Civic Deployment Mode",
        "Mr Naddaf Has Discovered Forty Seven Browser Tabs",
        "Joseph Naddaf Has Begun The Ancient IT Ritual",
        "Mr Naddaf Has Determined That The Power Strip Was Off",
        "Joseph Naddaf Has Entered The Printer Containment Zone",
        "Mr Naddaf Has Requested Administrator Access",
        "Joseph Naddaf Has Activated The Massage Chair Recovery Protocol",
        "Mr Naddaf Has Detected A Layer Eight Networking Failure",
        "Joseph Naddaf Has Been Informed That The Internet Is Broken",
        "Mr Naddaf Has Begun Staring At Task Manager",
        "Joseph Naddaf Has Located The Problem In Four Seconds",
        "Mr Naddaf Has Determined That Everything Was Changed",
        "Joseph Naddaf Has Arrived Carrying A Shawarma And An Ethernet Cable",
        "Mr Naddaf Has Successfully Survived Another IT Emergency",
        "Joseph Naddaf Has Entered The Forbidden Network Closet",
        "Mr Naddaf Has Initiated The Ten Second Unplugging Procedure",
        "Joseph Naddaf Has Been Summoned By The Sound Of A Failing Printer",
        "Mr Naddaf Has Taken The Keyboard Away",
        "Joseph Naddaf Has Activated Emergency Honda Civic Transportation",
        "Mr Naddaf Has Determined That Clicking It Again Will Not Help",
        "Joseph Naddaf Has Entered The Shawarma Powered Computing Era",
        "Mr Naddaf Has Successfully Found The File Nobody Could Find",
        "Joseph Naddaf Has Detected Unauthorized Router Touching",
        "Mr Naddaf Has Returned From Lunch With Increased Computing Power",
        "Joseph Naddaf Has Entered Full Technical Supremacy",
        "Mr Naddaf Has Diagnosed A Severe Case Of User Error",
        "Joseph Naddaf Has Restored Order To The Server Room",
        "Mr Naddaf Has Begun The Legendary Reboot Sequence",
        "Joseph Naddaf Has Activated Maximum Civic Horsepower",
        "Mr Naddaf Has Entered The Massage Chair Of Contemplation",
        "Joseph Naddaf Has Determined That This Could Have Been An Email",
        "Mr Naddaf Has Discovered The Monitor Was Not Turned On",
        "Joseph Naddaf Has Entered The Network Dimension",
        "Mr Naddaf Has Detected Something Extremely Ridiculous",
        "Joseph Naddaf Has Achieved Shawarma Assisted Troubleshooting",
        "Mr Naddaf Has Returned To Fix What Everyone Else Broke",
        "Joseph Naddaf Has Entered The Final Boss Fight Against The Printer",
        "Mr Naddaf Has Declared The Network Operational",
        "Joseph Naddaf Has Initiated The Great Router Restoration",
        "Mr Naddaf Has Finished Explaining What Restart Means",
        "Joseph Naddaf Has Entered A Completely Normal Day",
        "Mr Naddaf Has Achieved Honda Civic Synchronization",
        "Joseph Naddaf Has Determined That The Cable Was Never Plugged In",
        "Mr Naddaf Has Entered Unprecedented Levels Of IT Wizardry",
        "Joseph Naddaf Has Completed The Sacred Shawarma Cycle",
        "Mr Naddaf Has Successfully Prevented Another Technological Catastrophe",
        "Joseph Naddaf Has Returned And The Computers Are Afraid",
        "Joseph Naddaf Has Called IT Support And Waited On Hold",
        "Mr Naddaf Has Realigned The DNS Cache",
        "Joseph Naddaf Has Decided A Coffee Break Was Required",
        "Mr Naddaf Has Gone Looking For His Other Monitor",
        "Joseph Naddaf Has Realized The Fix Was Reinstall",
        "Mr Naddaf Has Sworn At The Command Line",
    ];

    public static readonly string[] Quotes =
    [
        "The Joseph Experience 2.0",
        "EXCELLENT WORK, MR. NADDAF.",
        "ANOTHER NADDAF CLASSIC.",
        "THE IT WIZARD STRIKES AGAIN.",
        "ABSOLUTELY TEXTBOOK, JOSEPH.",
        "SHAWARMA EARNED.",
        "CIVIC STATUS: DEPLOYED.",
        "THE NETWORK FEARS THIS MAN.",
        "PRINTER DEFEATED.",
        "ROUTER RESTORED.",
        "JOSEPH HAS ENTERED THE BUILDING.",
        "MR. NADDAF APPROVES.",
        "INCREDIBLE TECHNOLOGICAL PERFORMANCE.",
        "MASSAGE CHAIR PRIVILEGES RESTORED.",
        "ANOTHER SUCCESSFUL NADDAF OPERATION.",
        "THE SACRED RESTART WORKED.",
        "LAYER 8 ISSUE RESOLVED.",
        "IT WAS THE USER.",
        "THE CABLE WAS UNPLUGGED.",
        "THE MONITOR WAS OFF.",
        "SOMEHOW, JOSEPH FIXED IT AGAIN.",
        "TASK MANAGER HAS SPOKEN.",
        "THE SERVER ROOM IS SAFE.",
        "NADDAF MODE ACTIVATED.",
        "MAXIMUM JOSEPH ACHIEVED.",
        "SHAWARMA PROTOCOL COMPLETE.",
        "HONDA CIVIC READY FOR EXTRACTION.",
        "THE PRINTER HAS BEEN CONTAINED.",
        "TECHNICAL SUPREMACY ACHIEVED.",
        "THE INTERNET HAS BEEN RESTORED.",
        "THE ROUTER SURVIVED.",
        "THE USER DID NOT.",
        "ANOTHER TICKET DESTROYED.",
        "JOSEPH 1 — TECHNOLOGY 0.",
        "THE WIZARD HAS SPOKEN.",
        "CRISIS AVERTED.",
        "REBOOT SUCCESSFUL.",
        "ABSOLUTE IT CINEMA.",
        "CERTIFIED NADDAF MOMENT.",
        "THIS CALLS FOR A SHAWARMA.",
        "RETURN TO THE MASSAGE CHAIR.",
        "540 CURSEWAY REMAINS SECURE.",
        "THE CIVIC AWAITS.",
        "NOBODY TOUCH THE ROUTER.",
        "WHO CHANGED THE PASSWORD?",
        "WHY ARE THERE 47 TABS OPEN?",
        "HAVE YOU TRIED TURNING IT OFF AND ON AGAIN?",
        "JOSEPH ALREADY KNOWS WHAT YOU DID.",
        "THE COMPUTER STARTED WORKING OUT OF FEAR.",
        "HE FIXED IT BY LOOKING AT IT.",
        "ANOTHER IMPOSSIBLE PROBLEM SOLVED IN FOUR SECONDS.",
        "THE ETHERNET CABLE HAS BEEN LOCATED.",
        "ADMINISTRATOR ACCESS ACHIEVED.",
        "THE NETWORK BOWS BEFORE NADDAF.",
        "SHAWARMA-POWERED COMPUTING ENGAGED.",
        "PRINTER BOSS FIGHT COMPLETE.",
        "THE REBOOT WAS INEVITABLE.",
        "THIS SHOULD NOT HAVE REQUIRED IT.",
        "JOSEPH WAS RIGHT THE FIRST TIME.",
        "JOSEPH WAS ALSO RIGHT THE SECOND TIME.",
        "PLEASE STOP CLICKING IT.",
        "MR. NADDAF WILL HANDLE THIS.",
        "THE PROBLEM HAS BEEN PROFESSIONALLY STARED AT.",
        "ADVANCED DIAGNOSTICS COMPLETE.",
        "SUSPICIOUSLY EASY FIX.",
        "UNREASONABLY DIFFICULT FIX.",
        "SOMEONE OWES JOSEPH A SHAWARMA.",
        "GOOD JOB, JOSEPH. VERY GOOD JOB.",
    ];

    public static string RandomName() => Names[Random.Shared.Next(Names.Length)];
    public static string RandomQuote() => Quotes[Random.Shared.Next(Quotes.Length)];
}
